info:
  name: "@project.artifactId@"
  version: "@project.version@"
  description: "@project.description@"
  running-profile: "${spring.profiles.active}"

spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO}