info:
  name: "@project.artifactId@"
  version: "@project.version@"
  description: "@project.description@"
  running-profile: "${spring.profiles.active}"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CapabilityJavaArg/capability-configserver-repository.git